apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: bittuly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: bittuly/consumer-service:local
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: bittuly-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bittuly-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
