apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: bittuly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: bittuly/frontend-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bittuly
spec:
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 80
