services:
  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: bittuly-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: bittu
      RABBITMQ_DEFAULT_PASS: bittu
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: nginx:1.31.1-alpine
    container_name: bittuly-api-gateway
    network_mode: "host" # Allows NGINX to proxy to 127.0.0.1 on the host machine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      postgres-auth:
        condition: service_healthy
      postgres-urls:
        condition: service_healthy

  postgres-auth:
    image: postgres:17
    container_name: bittuly-postgres-auth
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: bittuly_auth
    ports:
      - "5432:5432"
    volumes:
      - bittuly-pg-auth-data:/var/lib/postgresql/data
      - ./docker/postgres-auth/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d bittuly_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-urls:
    image: postgres:17
    container_name: bittuly-postgres-urls
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: bittuly_urls
    ports:
      - "5433:5432"
    volumes:
      - bittuly-pg-urls-data:/var/lib/postgresql/data
      - ./docker/postgres-urls/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d bittuly_urls"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.7-bookworm
    container_name: bittuly-redis
    command: >
      redis-server
      --loglevel warning
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:v3-distroless
    container_name: bittuly-prometheus
    network_mode: "host"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.6
    container_name: bittuly-grafana
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  bittuly-pg-auth-data:
  bittuly-pg-urls-data:
