services:
  postgres-auth:
    image: postgres:17
    container_name: bittuly-postgres-auth
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: bittuly_auth
    ports:
      - "5432:5432"
    volumes:
      - bittuly-pg-auth-data:/var/lib/postgresql/data
      - ./docker/postgres_auth/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d bittuly_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-urls:
    image: postgres:17
    container_name: bittuly-postgres-urls
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: bittuly_urls
    ports:
      - "5433:5432"
    volumes:
      - bittuly-pg-urls-data:/var/lib/postgresql/data
      - ./docker/postgres_urls/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d bittuly_urls"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.2.7-bookworm
    container_name: bittuly-redis
    command: >
      redis-server
      --loglevel warning
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  bittuly-pg-auth-data:
  bittuly-pg-urls-data:
