apiVersion: v1
kind: Secret
metadata:
  name: bittuly-secrets
  namespace: bittuly
type: Opaque
stringData:
  # JWT — replace with `openssl rand -base64 32` for production
  JWT_SECRET: "zXoP9/N+yM2rG7K4lWfJ8QeA1D3b5c6vT0mHqYhI="

  # SMTP (only used when MODE=production)
  SMTP_USER: "bitweb26@gmail.com"
  SMTP_PASS: "vrve bmpl rzdm qwcu"

  # Database credentials
  POSTGRES_AUTH_PASSWORD: "bittu"
  POSTGRES_URLS_PASSWORD: "bittu"
  RABBITMQ_PASSWORD: "bittu"
